CREATE TABLE keys
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    payload     VARCHAR(32),
    owner_id    BIGINT,
    CONSTRAINT pk_keys PRIMARY KEY (id)
);

CREATE TABLE user_accessible_locks
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    lock_id VARCHAR(255),
    CONSTRAINT pk_user_accessible_locks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE keys
    ADD CONSTRAINT FK_KEYS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE user_accessible_locks
    ADD CONSTRAINT FK_USER_ACCESSIBLE_LOCKS_ON_LOCK FOREIGN KEY (lock_id) REFERENCES locks (id);

ALTER TABLE user_accessible_locks
    ADD CONSTRAINT FK_USER_ACCESSIBLE_LOCKS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);